# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
    build:
        docker:
            # This python image includes node 14.17.1 according to
            # https://circleci.com/developer/images/image/cimg/python#image-tags
            # It's a bit weird to use a python image when we care about node
            # first, but it's needed to get node-gyp to work to build iltorb
            - image: cimg/python:3.10.6-node

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            # run tests!
            - run: |
                  make test-ci

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
